server:
  port: 8080

spring:
  application:
    name: account-service
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_S3_BUCKET_NAME}

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
      acks: ${KAFKA_ACKS}
      retries: ${KAFKA_RETRIES}
      batch-size: 640000
      linger-ms: 5
      buffer-memory: 67108864
      properties:
        request.timeout.ms: ${KAFKA_REQUEST_TIMEOUT_MS}
        delivery.timeout.ms: ${KAFKA_DELIVERY_TIMEOUT_MS}
        max.block.ms: ${KAFKA_MAX_BLOCK_MS}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID}
      auto-offset-reset: latest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 5000
    listener:
      ack-mode: manual_immediate
      type: batch

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}

coolsms:
  api-key: ${COOLSMS_API_KEY}
  secret-key: ${COOLSMS_API_SECRET}
  sender-phone-number: ${COOLSMS_PHONE_NUMBER}
  domain: https://api.coolsms.co.kr

JWT:
  secret-key: ${JWT_SECRET}
  token:
    access-expire-time: ${ACCESS_TOKEN_EXPIRE_TIME}
    refresh-expire-time: ${REFRESH_TOKEN_EXPIRE_TIME}

feign:
  client:
    member-service:
      url: ${MEMBER_SERVICE_URL}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    config-url: /member-service/v3/api-docs/swagger-config
    url: /member-service/v3/api-docs
