server:
  port: 8080

spring:
  application:
    name: account-service
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_S3_BUCKET_NAME}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}

coolsms:
  api-key: ${COOLSMS_API_KEY}
  secret-key: ${COOLSMS_API_SECRET}
  sender-phone-number: ${COOLSMS_PHONE_NUMBER}
  domain: https://api.coolsms.co.kr

JWT:
  secret-key: ${JWT_SECRET}
  token:
    access-expire-time: ${ACCESS_TOKEN_EXPIRE_TIME}
    refresh-expire-time: ${REFRESH_TOKEN_EXPIRE_TIME}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    config-url: /member-service/v3/api-docs/swagger-config
    url: /member-service/v3/api-docs
