BEGIN;

CREATE TABLE IF NOT EXISTS grade (
    grade_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade_uuid VARCHAR(255) NOT NULL UNIQUE,
    grade_name VARCHAR(255) NOT NULL,
    min_point INTEGER NOT NULL,
    max_point INTEGER NOT NULL,
    description VARCHAR(255),
    order_number INTEGER NOT NULL UNIQUE,
    grade_image_key VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT ck_grade_point_range CHECK (min_point <= max_point)
);

CREATE TABLE IF NOT EXISTS grade_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_uuid VARCHAR(50) NOT NULL,
    post_uuid VARCHAR(255) NOT NULL,
    post_type VARCHAR(32) NOT NULL,
    point DOUBLE PRECISION NOT NULL,
    total_point DOUBLE PRECISION NOT NULL,
    grade_uuid VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

ALTER TABLE member ADD COLUMN IF NOT EXISTS grade_uuid VARCHAR(255);
ALTER TABLE member ADD COLUMN IF NOT EXISTS point DOUBLE PRECISION NOT NULL DEFAULT 100.0;

CREATE INDEX IF NOT EXISTS idx_grade_history_member_created
    ON grade_history (member_uuid, created_at DESC);

COMMIT;
